# Module 1 — Dataset & Document Processing

## Project
Evaluating Chunking and Retrieval Parameters for Answer Reliability
in RAG-Based AI/ML Research Paper Analysis

## Module Objective
Collect, extract, clean, and structure AI/ML research papers
for the RAG evaluation pipeline.

## Data Source
arXiv

## Initial Corpus
10 AI/ML research papers

# 1. Module 1 — Dataset & Document Processing

## 1.1 Module Objective

Collect, extract, clean, and structure AI/ML research papers
for the RAG evaluation pipeline.

## 1.2 Data Source

- Source: arXiv
- Domain: Artificial Intelligence & Machine Learning
- Initial Corpus: 10 research papers
- Document Format: Semantic HTML

## 1.3 Module Pipeline

Research Papers
      ↓
Paper Collection
      ↓
Metadata Extraction
      ↓
HTML/Text Extraction
      ↓
Text Cleaning
      ↓
Section Structuring
      ↓
Dataset Creation
      ↓
Quality Validation

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

PROJECT_DIR = "/content/drive/MyDrive/rag-evaluation-chunking-retrieval"

os.makedirs(PROJECT_DIR, exist_ok=True)

print("Project directory created:")
print(PROJECT_DIR)

Project directory created:
/content/drive/MyDrive/rag-evaluation-chunking-retrieval

In [ ]:
folders = [
    "data/raw",
    "data/processed",
    "data/metadata",
    "src/module1",
    "outputs/module1"
]

for folder in folders:
    os.makedirs(os.path.join(PROJECT_DIR, folder), exist_ok=True)

print("Module 1 project structure created successfully.")

Module 1 project structure created successfully.

In [ ]:
for root, dirs, files in os.walk(PROJECT_DIR):
    level = root.replace(PROJECT_DIR, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

rag-evaluation-chunking-retrieval/
    data/
        raw/
        processed/
        metadata/
    src/
        module1/
    outputs/
        module1/

# 2. Environment & Dependencies

The following Python libraries will be used for Module 1:

- requests
- BeautifulSoup
- pandas
- lxml
- json
- re
- os

In [ ]:
import pandas as pd
import os

papers = [
    {
        "paper_id": "P01",
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "arxiv_id": "2005.11401",
        "topic": "RAG"
    },
    {
        "paper_id": "P02",
        "title": "Dense Passage Retrieval for Open-Domain Question Answering",
        "arxiv_id": "2004.04906",
        "topic": "Information Retrieval"
    },
    {
        "paper_id": "P03",
        "title": "Retrieval-Augmented Generation for Large Language Models: A Survey",
        "arxiv_id": "2312.10997",
        "topic": "RAG Survey"
    },
    {
        "paper_id": "P04",
        "title": "RAGAS: Automated Evaluation of Retrieval Augmented Generation",
        "arxiv_id": "2309.15217",
        "topic": "RAG Evaluation"
    },
    {
        "paper_id": "P05",
        "title": "Lost in the Middle: How Language Models Use Long Contexts",
        "arxiv_id": "2307.03172",
        "topic": "Long Context"
    },
    {
        "paper_id": "P06",
        "title": "Attention Is All You Need",
        "arxiv_id": "1706.03762",
        "topic": "Transformer"
    },
    {
        "paper_id": "P07",
        "title": "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
        "arxiv_id": "1810.04805",
        "topic": "Language Model"
    },
    {
        "paper_id": "P08",
        "title": "Language Models are Few-Shot Learners",
        "arxiv_id": "2005.14165",
        "topic": "Large Language Model"
    },
    {
        "paper_id": "P09",
        "title": "LoRA: Low-Rank Adaptation of Large Language Models",
        "arxiv_id": "2106.09685",
        "topic": "LLM Fine-tuning"
    },
    {
        "paper_id": "P10",
        "title": "RAGChecker: A Fine-grained Framework for Diagnosing Retrieval-Augmented Generation",
        "arxiv_id": "2408.08067",
        "topic": "RAG Evaluation"
    }
]

metadata_df = pd.DataFrame(papers)

metadata_df

,paper_id,title,arxiv_id,topic
0,P01,Retrieval-Augmented Generation for Knowledge-I...,2005.11401,RAG
1,P02,Dense Passage Retrieval for Open-Domain Questi...,2004.04906,Information Retrieval
2,P03,Retrieval-Augmented Generation for Large Langu...,2312.10997,RAG Survey
3,P04,RAGAS: Automated Evaluation of Retrieval Augme...,2309.15217,RAG Evaluation
4,P05,Lost in the Middle: How Language Models Use Lo...,2307.03172,Long Context
5,P06,Attention Is All You Need,1706.03762,Transformer
6,P07,BERT: Pre-training of Deep Bidirectional Trans...,1810.04805,Language Model
7,P08,Language Models are Few-Shot Learners,2005.14165,Large Language Model
8,P09,LoRA: Low-Rank Adaptation of Large Language Mo...,2106.09685,LLM Fine-tuning
9,P10,RAGChecker: A Fine-grained Framework for Diagn...,2408.08067,RAG Evaluation

In [ ]:
metadata_path = os.path.join(
    PROJECT_DIR,
    "data/metadata/paper_metadata.csv"
)

metadata_df.to_csv(metadata_path, index=False)

print("Metadata saved successfully!")
print(metadata_path)

Metadata saved successfully!
/content/drive/MyDrive/rag-evaluation-chunking-retrieval/data/metadata/paper_metadata.csv

In [ ]:
pd.read_csv(metadata_path)

,paper_id,title,arxiv_id,topic
0,P01,Retrieval-Augmented Generation for Knowledge-I...,2005.11401,RAG
1,P02,Dense Passage Retrieval for Open-Domain Questi...,2004.04906,Information Retrieval
2,P03,Retrieval-Augmented Generation for Large Langu...,2312.10997,RAG Survey
3,P04,RAGAS: Automated Evaluation of Retrieval Augme...,2309.15217,RAG Evaluation
4,P05,Lost in the Middle: How Language Models Use Lo...,2307.03172,Long Context
5,P06,Attention Is All You Need,1706.03762,Transformer
6,P07,BERT: Pre-training of Deep Bidirectional Trans...,1810.04805,Language Model
7,P08,Language Models are Few-Shot Learners,2005.14165,Large Language Model
8,P09,LoRA: Low-Rank Adaptation of Large Language Mo...,2106.09685,LLM Fine-tuning
9,P10,RAGChecker: A Fine-grained Framework for Diagn...,2408.08067,RAG Evaluation

In [ ]:
!pip install requests beautifulsoup4 lxml

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (6.1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)

In [ ]:
import requests
import pandas as pd

def check_arxiv_html(arxiv_id):
    url = f"https://arxiv.org/html/{arxiv_id}"

    try:
        response = requests.get(url, timeout=15)

        if response.status_code == 200:
            return "Available"
        else:
            return f"Not Available ({response.status_code})"

    except Exception as e:
        return "Error"

metadata_df["html_status"] = metadata_df["arxiv_id"].apply(check_arxiv_html)

metadata_df[["paper_id", "arxiv_id", "html_status"]]

  paper_id    arxiv_id html_status
0      P01  2005.11401   Available
1      P02  2004.04906   Available
2      P03  2312.10997   Available
3      P04  2309.15217   Available
4      P05  2307.03172   Available
5      P06  1706.03762   Available
6      P07  1810.04805   Available
7      P08  2005.14165   Available
8      P09  2106.09685   Available
9      P10  2408.08067   Available

In [ ]:
import requests
import time

RAW_DIR = os.path.join(PROJECT_DIR, "data/raw")

download_results = []

for _, row in metadata_df.iterrows():

    paper_id = row["paper_id"]
    arxiv_id = row["arxiv_id"]

    url = f"https://arxiv.org/html/{arxiv_id}"
    output_file = os.path.join(
        RAW_DIR,
        f"{paper_id}_{arxiv_id}.html"
    )

    try:
        response = requests.get(url, timeout=30)

        if response.status_code == 200:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(response.text)

            download_results.append({
                "paper_id": paper_id,
                "arxiv_id": arxiv_id,
                "status": "Downloaded",
                "file": output_file,
                "size_kb": round(len(response.content) / 1024, 2)
            })

        else:
            download_results.append({
                "paper_id": paper_id,
                "arxiv_id": arxiv_id,
                "status": f"Failed ({response.status_code})",
                "file": "",
                "size_kb": 0
            })

    except Exception as e:
        download_results.append({
            "paper_id": paper_id,
            "arxiv_id": arxiv_id,
            "status": f"Error: {str(e)}",
            "file": "",
            "size_kb": 0
        })

    time.sleep(1)

download_df = pd.DataFrame(download_results)

download_df

,paper_id,arxiv_id,status,file,size_kb
0,P01,2005.11401,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,238.38
1,P02,2004.04906,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,213.98
2,P03,2312.10997,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,336.85
3,P04,2309.15217,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,102.01
4,P05,2307.03172,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,170.30
5,P06,1706.03762,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,184.28
6,P07,1810.04805,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,256.84
7,P08,2005.14165,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,1192.28
8,P09,2106.09685,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,494.05
9,P10,2408.08067,Downloaded,/content/drive/MyDrive/rag-evaluation-chunking...,414.69

In [ ]:
from bs4 import BeautifulSoup

p01_file = os.path.join(RAW_DIR, "P01_2005.11401.html")

with open(p01_file, "r", encoding="utf-8") as f:
    html_content = f.read()

print("HTML characters:", len(html_content))
print("\nFirst 1000 characters:\n")
print(html_content[:1000])

HTML characters: 243312

First 1000 characters:

<!DOCTYPE html><html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks</title>
<!--Generated by LaTeXML oxide (version 0.7.6) http://dlmf.nist.gov/LaTeXML/.-->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="/static/browse/0.3.4/css/arxiv-html-papers-20260823.css" type="text/css">
<script src="/static/browse/0.3.4/js/arxiv-html-papers-20260131.js"> </script>
<script>
  // Restore the saved color scheme preference, or
  // enact the browser preference if "automatic",
  // without expecting DOM load to have completed.
  //
  // Also restore any saved readingmode and ToC display preferences.
  function initializeReadingPreferences() {
    let saved_theme = localStorage.getItem("ar5iv_theme") || "automatic";
    if (saved_theme === "automatic") {
      if (window.matchMedia("(prefers-color-scheme: dark)").matches) {

In [ ]:
soup = BeautifulSoup(html_content, "html.parser")

print("Page title:")
print(soup.title.get_text(strip=True) if soup.title else "No title")

print("\nNumber of headings:")
print(len(soup.find_all(["h1", "h2", "h3", "h4"])))

print("\nHeadings found:")
for heading in soup.find_all(["h1", "h2", "h3", "h4"]):
    text = heading.get_text(" ", strip=True)
    if text:
        print(heading.name, "→", text)

Page title:
Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks

Number of headings:
49

Headings found:
h1 → Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
h2 → 1 Introduction
h2 → 2 Methods
h3 → 2.1 Models
h4 → RAG-Sequence Model
h4 → RAG-Token Model
h3 → 2.2 Retriever: DPR
h3 → 2.3 Generator: BART
h3 → 2.4 Training
h3 → 2.5 Decoding
h4 → RAG-Token
h4 → RAG-Sequence
h2 → 3 Experiments
h3 → 3.1 Open-domain Question Answering
h3 → 3.2 Abstractive Question Answering
h3 → 3.3 Jeopardy Question Generation
h3 → 3.4 Fact Verification
h2 → 4 Results
h3 → 4.1 Open-domain Question Answering
h3 → 4.2 Abstractive Question Answering
h3 → 4.3 Jeopardy Question Generation
h3 → 4.4 Fact Verification
h3 → 4.5 Additional Results
h4 → Generation Diversity
h4 → Retrieval Ablations
h4 → Index hot-swapping
h4 → Effect of Retrieving more documents
h2 → 5 Related Work
h4 → Single-Task Retrieval
h4 → General-Purpose Architectures for NLP
h4 → Learned Retrieval
h4 → Memory-based Architectures
h4 → Retrieve-and-Edit approaches
h2 → 6 Discussion
h2 → Broader Impact
h2 → Acknowledgments
h2 → References
h2 → Appendix A Implementation Details
h2 → Appendix B Human Evaluation
h2 → Appendix C Training setup Details
h2 → Appendix D Further Details on Open-Domain QA
h4 → CuratedTrec preprocessing
h4 → TriviaQA Evaluation setups
h2 → Appendix E Further Details on FEVER
h2 → Appendix F Null Document Probabilities
h2 → Appendix G Parameters
h2 → Appendix H Retrieval Collapse
h2 → Appendix I Number of instances per dataset
h2 → Instructions for reporting errors

In [ ]:
from bs4 import BeautifulSoup
import os
import pandas as pd


def extract_sections_from_html(html_file, paper_id):
    """
    Extract headings and their associated text from an arXiv HTML paper.
    """

    with open(html_file, "r", encoding="utf-8") as f:
        html_content = f.read()

    soup = BeautifulSoup(html_content, "html.parser")

    records = []

    headings = soup.find_all(["h1", "h2", "h3", "h4"])

    for heading in headings:

        section_title = heading.get_text(" ", strip=True)

        if not section_title:
            continue

        # Collect text until the next heading
        section_text = []

        for element in heading.find_all_next():

            if element.name in ["h1", "h2", "h3", "h4"]:
                break

            if element.name in ["p", "li"]:
                text = element.get_text(" ", strip=True)

                if text:
                    section_text.append(text)

        records.append({
            "paper_id": paper_id,
            "heading_level": heading.name,
            "section_title": section_title,
            "text": " ".join(section_text)
        })

    return pd.DataFrame(records)

In [ ]:
p01_sections = extract_sections_from_html(
    p01_file,
    "P01"
)

print("Number of extracted sections:", len(p01_sections))

p01_sections.head(15)

Number of extracted sections: 49

,paper_id,heading_level,section_title,text
0,P01,h1,Retrieval-Augmented Generation for Knowledge-I...,Large pre-trained language models have been sh...
1,P01,h2,1 Introduction,Pre-trained neural language models have been s...
2,P01,h2,2 Methods,"We explore RAG models, which use the input seq..."
3,P01,h3,2.1 Models,
4,P01,h4,RAG-Sequence Model,The RAG-Sequence model uses the same retrieved...
5,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different...
6,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\et...
7,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y ..."
8,P01,h3,2.4 Training,We jointly train the retriever and generator c...
9,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token requi..."
10,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard,..."
11,P01,h4,RAG-Sequence,"For RAG-Sequence, the likelihood p ⁡ ( y | x )..."
12,P01,h2,3 Experiments,We experiment with RAG in a wide range of know...
13,P01,h3,3.1 Open-domain Question Answering,Open-domain question answering (QA) is an impo...
14,P01,h3,3.2 Abstractive Question Answering,RAG models\ncan go beyond simple extractive QA...

In [ ]:
pd.set_option("display.max_colwidth", 150)

p01_sections[
    ["paper_id", "heading_level", "section_title", "text"]
].head(10)

,paper_id,heading_level,section_title,text
0,P01,h1,Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks,"Large pre-trained language models have been shown to store factual knowledge in their parameters, and achieve state-of-the-art results when fine-t..."
1,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data [ 47 ] .\nThey can do so without ...
2,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
3,P01,h3,2.1 Models,
4,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence . Technically, it treats the retrieved document as a sin..."
5,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
6,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\eta}(z|x) is based on DPR [ 26 ] . DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z...
7,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y 1 : i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART..."
8,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved.\nGiven a fine-tuning ...
9,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg ​ max y ⁡ p ​ ( y | x ) \argmax_{y}p(y|x) ."

In [ ]:
!pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from BeautifulSoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from BeautifulSoup4) (4.16.0)

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd


def extract_sections_from_html(html_file, paper_id):
    """
    Extract structured headings and paragraph/list text
    from an arXiv HTML paper.
    """

    with open(html_file, "r", encoding="utf-8") as f:
        html_content = f.read()

    soup = BeautifulSoup(html_content, "html.parser")

    records = []

    headings = soup.find_all(["h1", "h2", "h3", "h4"])

    for heading in headings:

        section_title = heading.get_text(" ", strip=True)

        if not section_title:
            continue

        section_text = []

        # Start from the elements immediately following this heading
        for element in heading.find_all_next():

            # Stop when another heading is reached
            if element.name in ["h1", "h2", "h3", "h4"]:
                break

            # Extract paragraph text
            if element.name == "p":
                text = element.get_text(" ", strip=True)

                if text:
                    section_text.append(text)

            # Extract list items
            elif element.name == "li":
                text = element.get_text(" ", strip=True)

                if text:
                    section_text.append(text)

        records.append({
            "paper_id": paper_id,
            "heading_level": heading.name,
            "section_title": section_title,
            "text": " ".join(section_text)
        })

    return pd.DataFrame(records)

In [ ]:
p01_sections = extract_sections_from_html(
    p01_file,
    "P01"
)

print("Number of extracted sections:", len(p01_sections))

p01_sections.head(15)

Number of extracted sections: 49

,paper_id,heading_level,section_title,text
0,P01,h1,Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks,"Large pre-trained language models have been shown to store factual knowledge in their parameters, and achieve state-of-the-art results when fine-t..."
1,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data [ 47 ] .\nThey can do so without ...
2,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
3,P01,h3,2.1 Models,
4,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence . Technically, it treats the retrieved document as a sin..."
5,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
6,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\eta}(z|x) is based on DPR [ 26 ] . DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z...
7,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y 1 : i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART..."
8,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved.\nGiven a fine-tuning ...
9,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg ​ max y ⁡ p ​ ( y | x ) \argmax_{y}p(y|x) ."
10,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard, autoregressive seq2seq generator with transition probability: p θ ′ ( y i | x , y 1 : i − 1 ) = ∑ z..."
11,P01,h4,RAG-Sequence,"For RAG-Sequence, the likelihood p ⁡ ( y | x ) p(y|x) does not break into a conventional per- token likelihood, hence we cannot solve it with a si..."
12,P01,h2,3 Experiments,"We experiment with RAG in a wide range of knowledge-intensive tasks. For all experiments, we use a single Wikipedia dump for our non-parametric kn..."
13,P01,h3,3.1 Open-domain Question Answering,Open-domain question answering (QA) is an important real-world application and common testbed for knowledge-intensive tasks [ 20 ] .\nWe treat que...
14,P01,h3,3.2 Abstractive Question Answering,"RAG models\ncan go beyond simple extractive QA\nand answer questions with free-form, abstractive text generation. To test RAG’s natural language g..."

In [ ]:
p01_sections[
    ["paper_id", "heading_level", "section_title", "text"]
].head(10)

,paper_id,heading_level,section_title,text
0,P01,h1,Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks,"Large pre-trained language models have been shown to store factual knowledge in their parameters, and achieve state-of-the-art results when fine-t..."
1,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data [ 47 ] .\nThey can do so without ...
2,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
3,P01,h3,2.1 Models,
4,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence . Technically, it treats the retrieved document as a sin..."
5,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
6,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\eta}(z|x) is based on DPR [ 26 ] . DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z...
7,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y 1 : i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART..."
8,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved.\nGiven a fine-tuning ...
9,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg ​ max y ⁡ p ​ ( y | x ) \argmax_{y}p(y|x) ."

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd


def extract_sections_from_html(html_file, paper_id):
    """
    Extract h2-h4 sections and their associated paragraph/list text
    from an arXiv Semantic HTML paper.
    """

    with open(html_file, "r", encoding="utf-8") as f:
        html_content = f.read()

    soup = BeautifulSoup(html_content, "html.parser")

    records = []

    # h1 is the paper title, so section extraction starts from h2
    headings = soup.find_all(["h2", "h3", "h4"])

    for heading in headings:

        section_title = heading.get_text(" ", strip=True)

        if not section_title:
            continue

        section_text = []

        for element in heading.find_all_next():

            # Stop at the next section heading
            if element.name in ["h2", "h3", "h4"]:
                break

            if element.name == "p":
                text = element.get_text(" ", strip=True)

                if text:
                    section_text.append(text)

            elif element.name == "li":
                text = element.get_text(" ", strip=True)

                if text:
                    section_text.append(text)

        records.append({
            "paper_id": paper_id,
            "heading_level": heading.name,
            "section_title": section_title,
            "text": " ".join(section_text)
        })

    return pd.DataFrame(records)

In [ ]:
p01_sections = extract_sections_from_html(
    p01_file,
    "P01"
)

print("Number of extracted sections:", len(p01_sections))

p01_sections.head(15)

Number of extracted sections: 48

,paper_id,heading_level,section_title,text
0,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data [ 47 ] .\nThey can do so without ...
1,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
2,P01,h3,2.1 Models,
3,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence . Technically, it treats the retrieved document as a sin..."
4,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
5,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\eta}(z|x) is based on DPR [ 26 ] . DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z...
6,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y 1 : i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART..."
7,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved.\nGiven a fine-tuning ...
8,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg ​ max y ⁡ p ​ ( y | x ) \argmax_{y}p(y|x) ."
9,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard, autoregressive seq2seq generator with transition probability: p θ ′ ( y i | x , y 1 : i − 1 ) = ∑ z..."
10,P01,h4,RAG-Sequence,"For RAG-Sequence, the likelihood p ⁡ ( y | x ) p(y|x) does not break into a conventional per- token likelihood, hence we cannot solve it with a si..."
11,P01,h2,3 Experiments,"We experiment with RAG in a wide range of knowledge-intensive tasks. For all experiments, we use a single Wikipedia dump for our non-parametric kn..."
12,P01,h3,3.1 Open-domain Question Answering,Open-domain question answering (QA) is an important real-world application and common testbed for knowledge-intensive tasks [ 20 ] .\nWe treat que...
13,P01,h3,3.2 Abstractive Question Answering,"RAG models\ncan go beyond simple extractive QA\nand answer questions with free-form, abstractive text generation. To test RAG’s natural language g..."
14,P01,h3,3.3 Jeopardy Question Generation,"To evaluate RAG’s generation abilities in a non-QA setting, we study open-domain question generation.\nRather than use questions from standard ope..."

In [ ]:
p01_sections[
    ["paper_id", "heading_level", "section_title", "text"]
].head(10)

,paper_id,heading_level,section_title,text
0,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data [ 47 ] .\nThey can do so without ...
1,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
2,P01,h3,2.1 Models,
3,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence . Technically, it treats the retrieved document as a sin..."
4,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
5,P01,h3,2.2 Retriever: DPR,The retrieval component p η ​ ( z | x ) p_{\eta}(z|x) is based on DPR [ 26 ] . DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z...
6,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x , z , y 1 : i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART..."
7,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved.\nGiven a fine-tuning ...
8,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg ​ max y ⁡ p ​ ( y | x ) \argmax_{y}p(y|x) ."
9,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard, autoregressive seq2seq generator with transition probability: p θ ′ ( y i | x , y 1 : i − 1 ) = ∑ z..."

In [ ]:
import re

def clean_text(text):
    """
    Clean extracted research-paper text.

    Removes:
    - newline and tab characters
    - invisible Unicode characters
    - numeric in-text citation markers such as [47], [12, 18], [1-3]

    Preserves:
    - scientific numbers
    - percentages
    - model names
    - equations/textual notation
    - technical terminology
    """

    if not isinstance(text, str):
        return ""

    # Replace newline and tab characters with spaces
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    # Remove invisible Unicode characters
    text = re.sub(r"[\u200b\u200c\u200d\ufeff]", "", text)

    # Remove numeric citation markers
    # Examples: [47], [12, 18], [1-3], [1, 2, 5-7]
    text = re.sub(
        r"\[\s*\d+(?:\s*[-–]\s*\d+)?(?:\s*,\s*\d+(?:\s*[-–]\s*\d+)?)*\s*\]",
        "",
        text
    )

    # Normalize multiple spaces
    text = re.sub(r"\s+", " ", text)

    # Remove spaces before punctuation
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)

    return text.strip()

In [ ]:
test_text = """
RAG was introduced in previous work [47].
Several methods [12, 18] were compared.
The model uses 384-dimensional embeddings and achieves 95% accuracy.
The approach was evaluated on datasets from 2020.
"""

print("BEFORE:")
print(test_text)

print("\nAFTER:")
print(clean_text(test_text))

BEFORE:

RAG was introduced in previous work [47].
Several methods [12, 18] were compared.
The model uses 384-dimensional embeddings and achieves 95% accuracy.
The approach was evaluated on datasets from 2020.


AFTER:
RAG was introduced in previous work. Several methods were compared. The model uses 384-dimensional embeddings and achieves 95% accuracy. The approach was evaluated on datasets from 2020.

In [ ]:
p01_sections_clean = p01_sections.copy()

p01_sections_clean["text"] = (
    p01_sections_clean["text"]
    .apply(clean_text)
)

p01_sections_clean.head(10)

,paper_id,heading_level,section_title,text
0,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data. They can do so without any acces...
1,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
2,P01,h3,2.1 Models,
3,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence. Technically, it treats the retrieved document as a sing..."
4,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
5,P01,h3,2.2 Retriever: DPR,The retrieval component p η ( z | x ) p_{\eta}(z|x) is based on DPR. DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z) is a den...
6,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x, z, y 1: i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART-la..."
7,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved. Given a fine-tuning t...
8,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg max y ⁡ p ( y | x ) \argmax_{y}p(y|x)."
9,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard, autoregressive seq2seq generator with transition probability: p θ ′ ( y i | x, y 1: i − 1 ) = ∑ z ∈..."

In [ ]:
for i in range(min(5, len(p01_sections_clean))):

    print("=" * 80)
    print("SECTION:", p01_sections_clean.iloc[i]["section_title"])
    print()
    print(p01_sections_clean.iloc[i]["text"][:1000])
    print()

================================================================================
SECTION: 1 Introduction

Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data. They can do so without any access to an external memory, as a parameterized implicit knowledge base. While this development is exciting, such models do have downsides: They cannot easily expand or revise their memory, can’t straightforwardly provide insight into their predictions, and may produce “hallucinations”. Hybrid models that combine parametric memory with non-parametric (i.e., retrieval-based) memories can address some of these issues because knowledge can be directly revised and expanded, and accessed knowledge can be inspected and interpreted. REALM and ORQA, two recently introduced models that combine masked language models with a differentiable retriever, have shown promising results, but have only explored open-domain extractive question answering. Here, we bring hybrid parametric and non-parametric memory to the “workhorse of NLP,” i.e. sequence-to-sequence (s

================================================================================
SECTION: 2 Methods

We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the target sequence y y. As shown in Figure 1, our models leverage two components: (i) a retriever p η ( z | x ) p_{\eta}(z|x) with parameters η \eta that returns (top-K truncated) distributions over text passages given a query x x and (ii) a generator p θ ( y i | x, z, y 1: i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) parametrized by θ \theta that generates a current token based on a context of the previous i − 1 i-1 tokens y 1: i − 1 y_{1:i-1}, the original input x x and a retrieved passage z z. To train the retriever and generator end-to-end, we treat the retrieved document as a latent variable. We propose two models that marginalize over the latent documents in different ways to produce a distribution over generated text. In one approach, RAG-Sequence, the model uses the same document to predict each target token. The second approach, RAG-Token, can p

================================================================================
SECTION: 2.1 Models



================================================================================
SECTION: RAG-Sequence Model

The RAG-Sequence model uses the same retrieved document to generate the complete sequence. Technically, it treats the retrieved document as a single latent variable that is marginalized to get the seq2seq probability p ⁡ ( y | x ) p(y|x) via a top-K approximation. Concretely, the top K documents are retrieved using the retriever, and the generator produces the output sequence probability for each document, which are then marginalized,

================================================================================
SECTION: RAG-Token Model

In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to choose content from several documents when producing an answer. Concretely, the top K documents are retrieved using the retriever, and then the generator produces a distribution for the next output token for each document, before marginalizing, and repeating the process with the following output token, Formally, we define: Finally, we note that RAG can be used for sequence classification tasks by considering the target class as a target sequence of length one, in which case RAG-Sequence and RAG-Token are equivalent.

In [ ]:
p01_final = p01_sections_clean[
    p01_sections_clean["text"].str.strip() != ""
].copy()

p01_final.reset_index(drop=True, inplace=True)

print("Original section records:", len(p01_sections_clean))
print("Non-empty section records:", len(p01_final))

Original section records: 48
Non-empty section records: 44

In [ ]:
PROCESSED_DIR = os.path.join(PROJECT_DIR, "data/processed")

p01_output_path = os.path.join(
    PROCESSED_DIR,
    "P01_sections_clean.csv"
)

p01_final.to_csv(
    p01_output_path,
    index=False,
    encoding="utf-8"
)

print("P01 pilot dataset saved successfully!")
print(p01_output_path)

P01 pilot dataset saved successfully!
/content/drive/MyDrive/rag-evaluation-chunking-retrieval/data/processed/P01_sections_clean.csv

In [ ]:
print(p01_final.shape)
p01_final.head(10)

(44, 4)

,paper_id,heading_level,section_title,text
0,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data. They can do so without any acces...
1,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
2,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence. Technically, it treats the retrieved document as a sing..."
3,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
4,P01,h3,2.2 Retriever: DPR,The retrieval component p η ( z | x ) p_{\eta}(z|x) is based on DPR. DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z) is a den...
5,P01,h3,2.3 Generator: BART,"The generator component p θ ( y i | x, z, y 1: i − 1 ) p_{\theta}(y_{i}|x,z,y_{1:i-1}) could be modelled using any encoder-decoder. We use BART-la..."
6,P01,h3,2.4 Training,We jointly train the retriever and generator components without any direct supervision on what document should be retrieved. Given a fine-tuning t...
7,P01,h3,2.5 Decoding,"At test time, RAG-Sequence and RAG-Token require different ways to approximate arg max y ⁡ p ( y | x ) \argmax_{y}p(y|x)."
8,P01,h4,RAG-Token,"The RAG-Token model can be seen as a standard, autoregressive seq2seq generator with transition probability: p θ ′ ( y i | x, y 1: i − 1 ) = ∑ z ∈..."
9,P01,h4,RAG-Sequence,"For RAG-Sequence, the likelihood p ⁡ ( y | x ) p(y|x) does not break into a conventional per- token likelihood, hence we cannot solve it with a si..."

In [ ]:
print("Shape:", p01_final.shape)

print("\nColumns:")
print(p01_final.columns.tolist())

print("\nPaper IDs:")
print(p01_final["paper_id"].unique())

print("\nEmpty text values:")
print(p01_final["text"].isna().sum())

print("\nEmpty strings:")
print((p01_final["text"].str.strip() == "").sum())

Shape: (44, 4)

Columns:
['paper_id', 'heading_level', 'section_title', 'text']

Paper IDs:
['P01']

Empty text values:
0

Empty strings:
0

In [ ]:
# Load the actual saved P01 CSV from Google Drive

p01_saved = pd.read_csv(p01_output_path)

print("Saved file loaded successfully!")
print("Shape:", p01_saved.shape)

print("\nColumns:")
print(p01_saved.columns.tolist())

print("\nFirst 5 records:")
display(p01_saved.head())

Saved file loaded successfully!
Shape: (44, 4)

Columns:
['paper_id', 'heading_level', 'section_title', 'text']

First 5 records:

,paper_id,heading_level,section_title,text
0,P01,h2,1 Introduction,Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data. They can do so without any acces...
1,P01,h2,2 Methods,"We explore RAG models, which use the input sequence x x to retrieve text documents z z and use them as additional context when generating the targ..."
2,P01,h4,RAG-Sequence Model,"The RAG-Sequence model uses the same retrieved document to generate the complete sequence. Technically, it treats the retrieved document as a sing..."
3,P01,h4,RAG-Token Model,In the RAG-Token model we can draw a different latent document for each target token and marginalize accordingly. This allows the generator to cho...
4,P01,h3,2.2 Retriever: DPR,The retrieval component p η ( z | x ) p_{\eta}(z|x) is based on DPR. DPR follows a bi-encoder architecture: where 𝐝 ⁡ ( z ) \mathbf{d}(z) is a den...

In [ ]:
# Final file integrity check

print("Paper IDs:", p01_saved["paper_id"].unique())
print("Empty text values:", p01_saved["text"].isna().sum())
print("Empty strings:", (p01_saved["text"].str.strip() == "").sum())

Paper IDs: ['P01']
Empty text values: 0
Empty strings: 0

In [ ]:
all_processed = []

for _, row in metadata_df.iterrows():
    paper_id = row["paper_id"]
    arxiv_id = row["arxiv_id"]

    # P01 will be handled separately
    if paper_id == "P01":
        continue

    html_file = os.path.join(
        RAW_DIR,
        f"{paper_id}_{arxiv_id}.html"
    )

    print(f"Processing {paper_id}...")

    # Extract sections from HTML
    sections = extract_sections_from_html(
        html_file,
        paper_id
    )

    # Apply NEW cleaning function
    sections["text"] = sections["text"].apply(clean_text)

    # Remove empty text rows
    sections = sections[
        sections["text"].str.strip() != ""
    ].copy()

    # Reset index
    sections.reset_index(drop=True, inplace=True)

    # Save processed paper
    output_path = os.path.join(
        PROCESSED_DIR,
        f"{paper_id}_sections_clean.csv"
    )

    sections.to_csv(
        output_path,
        index=False,
        encoding="utf-8"
    )

    all_processed.append(sections)

    print(
        f"{paper_id} completed → "
        f"{len(sections)} sections"
    )

print("\nP02–P10 processing completed.")

Processing P02...
P02 completed → 35 sections
Processing P03...
P03 completed → 50 sections
Processing P04...
P04 completed → 16 sections
Processing P05...
P05 completed → 31 sections
Processing P06...
P06 completed → 23 sections
Processing P07...
P07 completed → 43 sections
Processing P08...
P08 completed → 52 sections
Processing P09...
P09 completed → 40 sections
Processing P10...
P10 completed → 30 sections

P02–P10 processing completed.

In [ ]:
print("\nProcessing summary")
print("=" * 50)

for df in all_processed:
    paper_id = df["paper_id"].iloc[0]
    print(
        f"{paper_id}: "
        f"{len(df)} non-empty sections"
    )

Processing summary
==================================================
P02: 35 non-empty sections
P03: 50 non-empty sections
P04: 16 non-empty sections
P05: 31 non-empty sections
P06: 23 non-empty sections
P07: 43 non-empty sections
P08: 52 non-empty sections
P09: 40 non-empty sections
P10: 30 non-empty sections

In [ ]:
# Combine all 10 papers

all_papers = [p01_final] + all_processed

module1_dataset = pd.concat(
    all_papers,
    ignore_index=True
)

print("Final Module 1 dataset")
print("=" * 50)
print("Shape:", module1_dataset.shape)
print(
    "Number of papers:",
    module1_dataset["paper_id"].nunique()
)

Final Module 1 dataset
==================================================
Shape: (364, 4)
Number of papers: 10

In [ ]:
print("Paper distribution:")
print(
    module1_dataset["paper_id"]
    .value_counts()
    .sort_index()
)

print("\nMissing values:")
print(
    module1_dataset.isna().sum()
)

print("\nEmpty text:")
print(
    (module1_dataset["text"].str.strip() == "").sum()
)

Paper distribution:
paper_id
P01    44
P02    35
P03    50
P04    16
P05    31
P06    23
P07    43
P08    52
P09    40
P10    30
Name: count, dtype: int64

Missing values:
paper_id         0
heading_level    0
section_title    0
text             0
dtype: int64

Empty text:
0

In [ ]:
module1_output_path = os.path.join(
    PROCESSED_DIR,
    "all_papers_sections_clean.csv"
)

module1_dataset.to_csv(
    module1_output_path,
    index=False,
    encoding="utf-8"
)

print("Final Module 1 dataset saved:")
print(module1_output_path)

Final Module 1 dataset saved:
/content/drive/MyDrive/rag-evaluation-chunking-retrieval/data/processed/all_papers_sections_clean.csv

In [ ]:
# Final Module 1 verification

print("Shape:", module1_dataset.shape)

print("\nNumber of papers:",
      module1_dataset["paper_id"].nunique())

print("\nPapers:")
print(
    sorted(module1_dataset["paper_id"].unique())
)

print("\nMissing values:")
print(
    module1_dataset.isna().sum()
)

print("\nEmpty text:")
print(
    (module1_dataset["text"].str.strip() == "").sum()
)

Shape: (364, 4)

Number of papers: 10

Papers:
['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10']

Missing values:
paper_id         0
heading_level    0
section_title    0
text             0
dtype: int64

Empty text:
0

In [ ]:
p01_html_file = os.path.join(
    RAW_DIR,
    "P01_2005.11401.html"
)

p01_sections = extract_sections_from_html(
    p01_html_file,
    "P01"
)

p01_sections["text"] = p01_sections["text"].apply(clean_text)

p01_sections = p01_sections[
    p01_sections["text"].str.strip() != ""
].copy()

p01_sections.reset_index(drop=True, inplace=True)

p01_output_path = os.path.join(
    PROCESSED_DIR,
    "P01_sections_clean.csv"
)

p01_sections.to_csv(
    p01_output_path,
    index=False,
    encoding="utf-8"
)

print("P01 completed.")
print("Shape:", p01_sections.shape)

P01 completed.
Shape: (44, 4)

In [ ]:
# Combine updated P01 + P02–P10

all_papers = [p01_sections] + all_processed

module1_dataset = pd.concat(
    all_papers,
    ignore_index=True
)

print("Final Module 1 dataset")
print("=" * 50)
print("Shape:", module1_dataset.shape)
print("Number of papers:", module1_dataset["paper_id"].nunique())
print("\nPapers:")
print(sorted(module1_dataset["paper_id"].unique()))

Final Module 1 dataset
==================================================
Shape: (364, 4)
Number of papers: 10

Papers:
['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10']

In [ ]:
module1_output_path = os.path.join(
    PROCESSED_DIR,
    "all_papers_sections_clean.csv"
)

module1_dataset.to_csv(
    module1_output_path,
    index=False,
    encoding="utf-8"
)

print("Final dataset saved successfully!")
print(module1_output_path)

Final dataset saved successfully!
/content/drive/MyDrive/rag-evaluation-chunking-retrieval/data/processed/all_papers_sections_clean.csv

In [ ]:
# Final validation of Module 1 dataset

print("MODULE 1 FINAL VALIDATION")
print("=" * 50)

# 1. Dataset shape
print("Shape:", module1_dataset.shape)

# 2. Number of papers
print("Number of papers:", module1_dataset["paper_id"].nunique())

# 3. Check missing values
print("\nMissing values:")
print(module1_dataset.isnull().sum())

# 4. Check empty text
empty_text = (
    module1_dataset["text"]
    .str.strip()
    .eq("")
    .sum()
)

print("\nEmpty text rows:", empty_text)

# 5. Check citation markers
citation_pattern = r"\[\s*\d+(?:\s*[-–]\s*\d+)?(?:\s*,\s*\d+(?:\s*[-–]\s*\d+)?)*\s*\]"

citation_matches = module1_dataset[
    module1_dataset["text"].str.contains(
        citation_pattern,
        regex=True,
        na=False
    )
]

print("\nRows still containing numeric citation markers:",
      len(citation_matches))

# 6. Final paper list
print("\nPapers:")
print(sorted(module1_dataset["paper_id"].unique()))

print("\n" + "=" * 50)
print("VALIDATION COMPLETED")

MODULE 1 FINAL VALIDATION
==================================================
Shape: (364, 4)
Number of papers: 10

Missing values:
paper_id         0
heading_level    0
section_title    0
text             0
dtype: int64

Empty text rows: 0

Rows still containing numeric citation markers: 0

Papers:
['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10']

==================================================
VALIDATION COMPLETED

In [ ]:
# Remove References sections

module1_dataset = module1_dataset[
    ~module1_dataset["section_title"].str.strip().str.lower().str.startswith("references")
].copy()

module1_dataset.reset_index(drop=True, inplace=True)

print("References section removed.")
print("New shape:", module1_dataset.shape)

References section removed.
New shape: (354, 4)

In [ ]:
module1_dataset.to_csv(
    module1_output_path,
    index=False,
    encoding="utf-8"
)

print("Updated dataset saved successfully.")

Updated dataset saved successfully.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving module1_query_set.csv to module1_query_set.csv

In [ ]:
import os
import shutil

# Existing Module 1 project directory
PROJECT_DIR = "/content/drive/MyDrive/rag-evaluation-chunking-retrieval"

# Query dataset folder
QUERY_DIR = os.path.join(PROJECT_DIR, "data", "metadata")

# Create folder if it does not exist
os.makedirs(QUERY_DIR, exist_ok=True)

# Uploaded CSV filename
source_path = "/content/module1_query_set.csv"

# Destination path in Google Drive
destination_path = os.path.join(
    QUERY_DIR,
    "module1_query_set.csv"
)

# Copy CSV into the project
shutil.copy2(source_path, destination_path)

print("Query set saved successfully!")
print("Location:", destination_path)

Query set saved successfully!
Location: /content/drive/MyDrive/rag-evaluation-chunking-retrieval/data/metadata/module1_query_set.csv

In [ ]:
import pandas as pd

query_path = os.path.join(
    QUERY_DIR,
    "module1_query_set.csv"
)

query_df = pd.read_csv(query_path)

print("QUERY DATASET VALIDATION")
print("=" * 40)

print("Shape:", query_df.shape)
print("Total questions:", len(query_df))

print("\nColumns:")
print(query_df.columns.tolist())

print("\nQuestions by category:")
print(query_df["category"].value_counts())

print("\nFirst 5 questions:")
display(query_df.head())

QUERY DATASET VALIDATION
========================================
Shape: (35, 8)
Total questions: 35

Columns:
['query_id', 'questions', 'category', 'expected_answer', 'supporting_paper_ids', 'supporting_sections', 'answerability', 'reason_unanswerable']

Questions by category:
category
direct            10
multi-document     8
reasoning          7
unanswerable       5
comparison         5
Name: count, dtype: int64

First 5 questions:

,query_id,questions,category,expected_answer,supporting_paper_ids,supporting_sections,answerability,reason_unanswerable
0,Q001,What problem does Retrieval-Augmented Generati...,direct,RAG combines a parametric language model with ...,P01,Introduction; Methods,Yes,NaN
1,Q002,What are the two main components combined in t...,direct,A pre-trained sequence-to-sequence generator a...,P01,Methods,Yes,NaN
2,Q003,What task does Dense Passage Retrieval (DPR) t...,direct,Open-domain question answering by retrieving r...,P02,Introduction; Methods,Yes,NaN
3,Q004,What is the main purpose of RAGAS?,direct,To provide automated evaluation of retrieval-a...,P04,Introduction; Methods,Yes,NaN
4,Q005,What issue is investigated in 'Lost in the Mid...,direct,The paper investigates how language models use...,P05,Introduction; Results,Yes,NaN